#define DIR_TYPE models
#define INSTALL_TO models/cogHQ

#begin flt_egg
  #define SOURCES $[wildcard *.flt]
#end flt_egg

#begin maya_egg
  #define SOURCES $[wildcard *.mb]
#end maya_egg

// gagTank was moved for CogThief Game to phase 4
#begin install_egg
  #define SOURCES \
    gagTank.egg
  #define PHASE 4
#end install_egg

// Begin cogHQ
#begin install_egg
  #define SOURCES \
    Elevator.egg alphaCone2.egg\
    platform1.egg metalCrate.egg FloorWear.egg \
    FactoryGearB.egg metal_crateB.egg \
    square_stomper.egg \
    woodCrate_cube.egg woodCrateB.egg \
    CogDoor_Button.egg FactoryGearBpost.egg \
    StairTen3060_15wide.egg StairTen45.egg StairTen3060.egg \
    CogDoorHandShake.egg \
    PaintMixer.egg BossRoomHQ.egg cube_tenfoot.egg \
    // Final model names
    SellbotFactoryExterior.egg SellbotHQLobby.egg SellbotHQExterior.egg SelbotLegFactory.egg \
    cog_sky.egg cogHQ_elevator.egg
  #if $[LANGUAGE]
    #define SOURCES $[SOURCES] \
      sellbotHQsign_$[LANGUAGE].egg
  #else
    #define SOURCES $[SOURCES] \
      sellbotHQsign.egg
  #endif
  #define PHASE 9
#end install_egg

// Begin cogHQ phase 6
#begin install_egg
  #define SOURCES \
    SmokeStack_simple.egg WaterTowerSimple.egg Cog_Tunnel.egg
  #define PHASE 6
#end install_egg

// Begin cashbotHQ phase 10
#begin install_egg
  #define SOURCES \
    CashBotFlatCar.egg \
    CashBotBossEyes.egg \
    RoundShadow.egg \
    SquareShadow.egg	
  #if $[eq $[LANGUAGE], german]
    #define SOURCES $[SOURCES] \
      CashBotShippingStation_german.egg \
	  CashBotLocomotive_german.egg \
	  CashBotBoxCar_german.egg \
	  CashBotTankCar_german.egg \
	  VaultLobby_german.egg \
	  MidVault_german.egg \
	  EndVault_german.egg \
	  CFOElevator_german.egg \
	  DoubleMoneyStack_german.egg \
	  CBMetalCrate2_german.egg \
	  mintElevator_german.egg
  #elif $[eq $[LANGUAGE], french]
    #define SOURCES $[SOURCES] \
      CashBotShippingStation_french.egg \
	  CashBotLocomotive_french.egg \
	  CashBotBoxCar_french.egg \
	  CashBotTankCar_french.egg \
	  VaultLobby_french.egg \
	  MidVault_french.egg \
	  EndVault_french.egg \
	  CFOElevator_french.egg \
	  DoubleMoneyStack_french.egg \
	  CBMetalCrate2_french.egg \
	  mintElevator_french.egg
  #else
    #define SOURCES $[SOURCES] \
      CashBotShippingStation_english.egg \
	  CashBotLocomotive_english.egg \
	  CashBotBoxCar_english.egg \
	  CashBotTankCar_english.egg \
	  VaultLobby_english.egg \
	  MidVault_english.egg \
	  EndVault_english.egg \
	  CFOElevator_english.egg \
	  DoubleMoneyStack_english.egg \
	  CBMetalCrate2_english.egg \
	  mintElevator_english.egg
  #endif
  #define PHASE 10
#end install_egg

#begin install_egg
  // These egg files were generated by hand.
  #define SOURCES \
    CBLightning.egg CBMagnet.egg CBSafe.egg CBCraneArm.egg \
    CBCraneControls.egg CBCraneStick.egg
  #define PHASE 10
#end install_egg
